config/routes.rb
Chno::Application.routes.draw do
  root 'events#index'

  resources :events do
    resources :projects
  end

  resources :users

  get '/signin', to: "sessions#new"
  post "/signin", to: "sessions#create"
end

app/models/event.rb
class Event < ActiveRecord::Base
  validates :name, presence: true
  has_many :projects, dependent: :delete_all
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :event
  validates :title, presence: true
  validates :description, presence: true, length: { minimum: 10 }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  
  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)

    if @event.save
      flash[:notice] = "Event has been created."
      redirect_to @event
    else
      flash[:alert] = "Event has not been created."
      render 'new'
    end
  end

  def show
    # see set_event
  end

  def edit
    # see set_event
  end

  def update
    # see set_event
    if @event.update(event_params)
      flash[:notice] = "Event has been updated."
      redirect_to @event
    else
      flash[:notice] = "Event has not been updated."
      render 'edit'
    end
  end

  def destroy
    # see set_event)
    @event.destroy

    flash[:notice] = "Event has been destroyed."

    redirect_to events_path
  end

  private

    def event_params
      params.require(:event).permit(:name, :description)
    end

    def set_event
      @event = Event.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash[:alert] = "The event you were looking for could not be found."
      redirect_to events_path
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_event
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def new
    @project = @event.projects.build
  end

  def create
    @project = @event.projects.build(project_params)
    if @project.save
      flash[:notice] = "Project has been created."
      redirect_to [@event, @project]
    else
      flash[:notice] = "Project has not been created."
      render 'new'
    end
  end

  def edit
  end

  def update
    if @project.update(project_params)
      flash[:notice] = "Project has been udpated."
      redirect_to [@event, @project]
    else
      flash[:alert] = "Project has not been updated."
      render action: 'edit'
    end
  end

  def destroy
    @project.destroy
    flash[:notice] = "Project has been deleted."
    redirect_to @event
  end

  private

    def set_event
      @event = Event.find(params[:event_id])
    end

     def project_params
      params.require(:project).permit(:title, :description)
    end

    def set_project
      @project = @event.projects.find(params[:id])
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.where(:name => params[:signin][:name]).first

    if user && user.authenticate(params[:signin][:password])
      session[:user_id] = user.id
      flash[:notice] = "Welcome, #{user.name}. Signed in successfully."
      
      redirect_to root_url
    else
      flash[:error] = "Nope."
      render :new
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def index
    @users = User.all
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:notice] = "You have signed up successfully."
      redirect_to users_path
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)  
      flash[:notice] = "Profile has been updated."
      redirect_to @user
    else
      flash[:notice] = 'Profile has not been updated.'
      render 'edit'
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(*parts)
    unless parts.empty?
      content_for :title do
        (parts << "CHNO").join(" : ")
      end
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
<% if @event.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@event.errors.count, "error") %>
       prohibited this event from being saved:
    </h2>
    <ul>
      <% @event.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
       <% end %>
    </ul>
  </div>
<% end %>

<p>
  <%= f.label :name %><br />
  <%= f.text_field :name %>
</p>

<p>
  <%= f.label :description %><br />
  <%= f.text_field :description %>
  <%= f.submit %>
</p>
<% end %>

app/views/events/edit.html.erb
<h2>Edit Event</h2>

<%= render "form" %>

app/views/events/index.html.erb
<%= link_to "New Event", new_event_path %>

<h2>Events</h2>
<ul>
  <% @events.each do |event| %>
    <li><%= link_to event.name, event %>
  <% end %>
</ul>

app/views/events/new.html.erb
<%= form_for(@event) do |f| %>
<% if @event.errors.any? %>
 <div id="error_explanation">
   <h2><%= pluralize(@event.errors.count, "error") %>
     prohibited this event from being saved:</h2>
   <ul>
   <% @event.errors.full_messages.each do |msg| %>
     <li><%= msg %></li>
   <% end %>
   </ul>
 </div>
<% end %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
</p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  <%= f.submit %>
<% end %>

app/views/events/show.html.erb
<% title(@event.name, "Events") %>

<h2><%= @event.name %></h2>
<%= link_to "Edit Event", edit_event_path(@event) %>
<%= link_to "Delete Event", 
    event_path(@event),
    method: :delete,
    data: { confirm:
            "Are you sure you want to delete this event?"
          } %>

<%= link_to "New Project", new_event_project_path(@event) %>
<ul id='projects'>
  <% @event.projects.each do |project| %>
  <li>
    #<%= project.id %> - <%= link_to project.title, [@event, project] %>
  </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    <% if content_for?(:title) %>
      <%= yield(:title) %>
    <% else %>
      CHNO
    <% end %>
  </title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |key, value| %>
  <div class='flash' id='<%= key %>'>
    <%= value %>
  </div>
<% end %>
<nav> 
  <ul>
    <li><%= link_to "Sign up", new_user_path %></li>
    <li><%= link_to "Sign in", signin_path %></li>
  </ul>
</nav>
<%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for [@event, @project] do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@project.errors.count, "error") %>
        prohibited this project from being saved:
      </h2>
      <ul>
        <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p> 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
  <%= f.submit %>
<% end %>

app/views/projects/edit.html.erb
<h2>Edit Project</h2>

<%= render "form" %>

app/views/projects/new.html.erb
<h2>New Project</h2>

<%= render "form" %>

app/views/projects/show.html.erb
<div id='project'>
  <h2><%= @project.title %></h2>
  <%= simple_format(@project.description) %>

  <%= link_to "Edit Project", [:edit, @event, @project] %>
  <%= link_to "Delete Project", [@event, @project],
              method: :delete,
              data: { 
                confirm: "Are you sure you want to delete this project?"
              }
  %>
</div>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
   <div id="error_explanation">
     <h2><%= pluralize(@user.errors.count, "error") %>
       prohibited this user from being saved:</h2>
     <ul>
     <% @user.errors.full_messages.each do |msg| %>
       <li><%= msg %></li>
     <% end %>
     </ul>
   </div>
  <% end %>
  <p>
    <%= f.label :name, "Username" %><br>
    <%= f.text_field :name %>
  </p> 
  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </p>
  <% if @user.new_record? %>
    <%= f.submit "Sign up" %>
  <% else %>
    <%= f.submit "Update Profile" %>
  <% end %>
<% end %>

app/views/users/edit.html.erb
<h2>Edit Profile</h2>

<%= render "form" %>

app/views/users/index.html.erb
<%= link_to "New User", new_user_path %>

<h2>Users</h2>
<ul>
  <% @users.each do |user| %>
    <li><%= link_to user.name, user %>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render "form" %>

app/views/users/show.html.erb
<div id='user'>
  <%= @user.name %>
  <%= @user.email %>

  <%= link_to "Edit Profile", edit_user_path(@user) %>
</div>